name: Build and Test

on:
  push:
    branches-ignore:
      - 'master'
      - 'sandbox'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: mvn package -s .maven/settings.xml
        env:
          PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
          PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
