name: Build and Test

on:
  push:
    branches-ignore:
      - 'master'
      - 'sandbox'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Write config file
        run: 'echo "$SANDBOX_ENV_FILE" > src/main/resources/config/configuration.yaml'
        shell: bash
        env:
          SANDBOX_ENV_FILE: ${{ secrets.SANDBOX_CONFIG }}
      - name: Build and test
        run: mvn -B package -Danypoint.platform.autodiscovery=$AUTODISCOVERY_ID -s .maven/settings.xml
        env:
          PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
          PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          AUTODISCOVERY_ID: '17300904'
