name: Build and Test

on:
  push:
    branches-ignore: [ master, sandbox ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: mvn package
