name: Build and Test

on:
  push:
    branches:
      - 'sandbox'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy
        run: mvn -B deploy -DmuleDeploy -s .maven/settings.xml
        env:
          PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
          PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          APP_NAME: 'sandbox-tshirt-mullet-293048-v1'
          PLATFORM_ENV: 'Sandbox'
          BUSINESS_GROUP_ID: '4018b97a-f1c2-4169-83c0-213563b05e04'
          PLATFORM_CLIENT_ID: ${{ secrets.SANDBOX_CLIENT_ID }}
          PLATFORM_CLIENT_SECRET: ${{ secrets.SANDBOX_CLIENT_SECRET }}