name: Build and Test

on:
  push:
    branches:
      - 'sandbox'


jobs:
  build-and-deploy-sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Write config file
        run: 'echo "$SANDBOX_ENV_FILE" > src/main/resources/config/configuration.yaml'
        shell: bash
        env:
          SANDBOX_ENV_FILE: ${{ secrets.SANDBOX_CONFIG }}
      - name: Build and deploy
        run: mvn -B deploy -DskipTests -DmuleDeploy -s .maven/settings.xml
        env:
          PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
          PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          APP_NAME: 'sandbox-tshirt-mullet-293048-v1'
          PLATFORM_ENV: 'Sandbox'
          BUSINESS_GROUP_ID: '4018b97a-f1c2-4169-83c0-213563b05e04'
          PLATFORM_CLIENT_ID: ${{ secrets.SANDBOX_CLIENT_ID }}
          PLATFORM_CLIENT_SECRET: ${{ secrets.SANDBOX_CLIENT_SECRET }}
          AUTODISCOVERY_ID: '17300904'